name: Prerelease

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version: "20.x"

      - run: yarn
      - run: yarn zl
        working-directory: ts-sandbox
      - run: yarn md5
        working-directory: ts-sandbox
